<!DOCTYPE html>
<html lang="en">
    <head>
        <base href="/new_shop/" />
        <link rel="stylesheet" href="style1.css" type="text/css"/>
        <meta charset="UTF-8" />
        <title><?= $title ?></title>
        <meta name="description" content="<?= $description ?>" />
    </head>

    <body>
        <header>
            <h1>Simple shop</h1>
        </header>

        <?php foreach ($messages as $message) : ?>
            <p class="message"><?= $message ?></p>
        <?php endforeach ?>
        
        <nav>
            <ul>
                <li><a href="home">Home</a></li>
                <li><a href="registration">Registration</a></li>
                <li><a href="reports">Reports</a></li>
                <li><a href="search">Search</a></li>
            </ul>
        </nav>
        <br />

        <!-- <article> -->
        <?php $this->controller->renderView();?>
        <!-- </article> -->

        <footer>
            <p>This is a test project implementing MVC architecture.</p>
        </footer>
    </body>
</html>